services:
  spotify-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify-scraper-service
    ports:
      - "3020:3020"
    environment:
      - PORT=3020
      - PYTHONPATH=/app
    volumes:
      - .:/app
      - /app/__pycache__
    working_dir: /app
    command: gunicorn --bind 0.0.0.0:3020 --workers 1 app:app
    restart: unless-stopped

networks:
  default:
    name: spotify-scraper-network